### ISSUE TITLE
Failed to call frontend_event_callback for frontend API

### ISSUE THREAD

**Issue by seansaephan** [redraskal/obs-replay-folders#1]
Hi,

I installed the script on OBS but when I clip it says the following error: 

[OBSReplayFolders.lua] Failed to call frontend_event_callback for frontend API: ...olders-main/obs-replay-folders-main/OBSReplayFolders.lua:49: attempt to perform arithmetic on local 'j' (a nil value)

I currently have the source on Game Capture named Game Capture.

Thank you.

**Comment by paper-alpaca** [comment]
Hello,

same problem here.
I tried to fix/debug the issue, but unfortunately, without success.
The only thing I could find is that the function get_game_capture_window_name is not able to assign values to its variables, which will be empty and then the string.sub fails.

Thank you

**Comment by redraskal** [comment]
Hey all, I found the issue.

The method I use actually fetches the manually selected window name.

I'm looking into a way to fetch the current window title. It's located here https://github.com/obsproject/obs-studio/blob/3de564258d6b9b6ba2e90c6fe7ffb78aa51c169d/plugins/win-capture/game-capture.c#L142.

This might not be possible with Lua. I may need to instead write an OBS plugin.

**Comment by redraskal** [comment]
I fixed the problem while keeping Lua, however, there is an issue. A command prompt window opens every time the script checks the current video game title. So, the script will only check the game title when the script is loaded and when the replay buffer is started.

So, you will have to toggle Replay Buffer every time you switch games.

**Comment by redraskal** [comment]
Also- you need to download detect_game.exe and add it to Windows PATH. This is inconvenient, but I have not found a better solution than to just externally detect the game.

**Comment by redraskal** [comment]
and fyi- the game capture source name is no longer relevant

**Comment by redraskal** [comment]
update: i fixed the inconvenience, it now chooses the right folder automatically. you just need to keep the dll file in the same folder as the script
